name: deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Push to dokku
              uses: dokku/github-action@6a74219fbab2441a36df6a32a61d72f05d43a21b # master
              with:
                  branch: main
                  git_remote_url: "ssh://dokku@github-bot.eslint.org/eslint-github-bot"
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
